on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: arc-runner
    steps:
      - name: Setup Secrets
        run: |
          github_app_id="$(cat /secrets/github-app-id)"
          echo "::add-mask::$github_app_id"
          echo "GITHUB_APP_ID=$github_app_id" >> "$GITHUB_ENV"
          private_key="$(cat /secrets/github-private-key | base64 -d)"
          while read -r line;
          do
            echo "::add-mask::${line}";
          done <<< $private_key
          {
            echo 'GITHUB_PRIVATE_KEY<<EOF'
            echo "$private_key"
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          private-key: ${{ env.GITHUB_PRIVATE_KEY }}
          app-id: ${{ env.GITHUB_APP_ID }}
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: google-github-actions/release-please-action@v4
        with:
          token: "${{ steps.get_token.outputs.token }}"
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
